# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BARC|Boydens Architech Model
email: chinh.trieutien@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Boydens Architech Model with Autodesk Revit for BIM
baseurl: "/BARC" # the subpath of your site, e.g. /blog
url: "http://chinh-trieutien.github.io" # the base hostname & protocol for your site
#twitter:
#  username: 
github_username:  chinh-trieutien

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins_dir:
  - jekyll-seo-tag
